apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gapit3-gwas-single-trait
  namespace: runai-talmo-lab
spec:
  # ===========================================================================
  # GAPIT3 GWAS - Single Trait WorkflowTemplate
  # ===========================================================================
  # Reusable template for running GWAS on a single trait
  # Reference from workflows using: templateRef.name: gapit3-gwas-single-trait
  # ===========================================================================

  entrypoint: run-gwas
  serviceAccountName: default  # Required for workflowtaskresults permission

  # Template-level arguments with defaults
  arguments:
    parameters:
    - name: trait-index
      value: "2"
    - name: trait-name
      value: "unknown"
    - name: image
      value: "ghcr.io/salk-harnessing-plants-initiative/gapit3-gwas-pipeline:sha-bc10fc8-test"
    - name: models
      value: "BLINK,FarmCPU"

  templates:
  # ===========================================================================
  # Main GWAS execution template
  # ===========================================================================
  # IMPORTANT: This template requires the calling workflow to define volumes:
  #   - nfs-data: Mounted at /data (read-only) for genotype/phenotype files
  #   - nfs-outputs: Mounted at /outputs (read-write) for GWAS results
  # See gapit3-test-pipeline.yaml for example volume configuration
  # ===========================================================================
  - name: run-gwas
    inputs:
      parameters:
      - name: trait-index
      - name: trait-name
      - name: image
      - name: models

    metadata:
      labels:
        app: gapit3-gwas
        component: single-trait
        trait-index: "{{inputs.parameters.trait-index}}"
      annotations:
        # Run.AI annotations for cluster scheduling
        runai/preemptible: "true"  # Allow preemption for better cluster utilization

    container:
      image: "{{inputs.parameters.image}}"
      imagePullPolicy: Always

      # Entrypoint command - configuration is passed via environment variables (env section below)
      # The entrypoint.sh script reads from env vars, NOT CLI args
      command: ["/scripts/entrypoint.sh"]
      args:
        - "run-single-trait"

      # Volume mounts
      volumeMounts:
      - name: nfs-data
        mountPath: /data
        readOnly: true  # Genotype/phenotype are read-only
      - name: nfs-outputs
        mountPath: /outputs
        readOnly: false

      # Environment variables
      env:
      - name: GENOTYPE_FILE
        value: "/data/genotype/acc_snps_filtered_maf_perl_edited_diploid.hmp.txt"
      - name: PHENOTYPE_FILE
        value: "/data/phenotype/iron_traits_edited.txt"
      - name: ACCESSION_IDS_FILE
        value: "/data/metadata/ids_gwas.txt"
      - name: MODELS
        value: "{{inputs.parameters.models}}"
      - name: OPENBLAS_NUM_THREADS
        value: "12"
      - name: OMP_NUM_THREADS
        value: "12"
      - name: TRAIT_INDEX
        value: "{{inputs.parameters.trait-index}}"
      - name: TRAIT_NAME
        value: "{{inputs.parameters.trait-name}}"
      - name: WORKFLOW_NAME
        value: "{{workflow.name}}"
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name

      # Resource allocation - increased for large datasets (1.4M+ SNPs, 2.2GB genotype file)
      # Note: Resources must be fixed values in WorkflowTemplates when using templateRef
      resources:
        requests:
          memory: "64Gi"
          cpu: "12"
        limits:
          memory: "72Gi"  # Headroom for peak memory during numericalization
          cpu: "16"       # Allow burst to 16 cores

    # Retry strategy for transient failures
    retryStrategy:
      limit: 5  # Retry up to 5 times (6 total attempts)
      retryPolicy: "OnFailure"
      backoff:
        duration: "2m"      # Wait 2 minutes before first retry
        factor: 2           # Double wait time for each retry
        maxDuration: "30m"  # Max wait time

    # Note: Artifact storage not configured on cluster
    # Results are saved directly to mounted volume at /outputs/trait_*/
