apiVersion: batch/v1
kind: Job
metadata:
  name: gapit3-gwas-trait-{{ TRAIT_INDEX }}
  labels:
    app: gapit3-gwas
    pipeline: arabidopsis-iron-traits
    trait-index: "{{ TRAIT_INDEX }}"
    batch-id: "{{ BATCH_ID }}"
spec:
  backoffLimit: 2  # Retry up to 2 times on failure
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
  template:
    metadata:
      labels:
        app: gapit3-gwas
        trait-index: "{{ TRAIT_INDEX }}"
    spec:
      restartPolicy: OnFailure

      # Resource allocation - Critical for memory-intensive GWAS
      containers:
      - name: gapit3-gwas
        image: ghcr.io/salk-harnessing-plants-initiative/gapit3-gwas-pipeline:latest
        imagePullPolicy: Always

        # Command - configuration is passed via environment variables (env section below)
        # The entrypoint.sh script reads from env vars, NOT CLI args
        command: ["/scripts/entrypoint.sh"]
        args:
          - "run-single-trait"

        # Resource requests and limits
        resources:
          requests:
            memory: "32Gi"    # Minimum required (per guide)
            cpu: "12"          # Request 12 cores
          limits:
            memory: "36Gi"    # Allow some headroom
            cpu: "16"          # Allow burst to 16 cores

        # Environment variables - ALL configuration is passed here
        # Parameter naming follows GAPIT v3.0.0 conventions (see docs/GAPIT_PARAMETERS.md)
        env:
        - name: OPENBLAS_NUM_THREADS
          value: "12"
        - name: OMP_NUM_THREADS
          value: "12"
        - name: TRAIT_INDEX
          value: "{{ TRAIT_INDEX }}"
        - name: BATCH_ID
          value: "{{ BATCH_ID }}"
        - name: GENOTYPE_FILE
          value: "/data/genotype/acc_snps_filtered_maf_perl_edited_diploid.hmp.txt"
        - name: PHENOTYPE_FILE
          value: "/data/phenotype/iron_traits_edited.txt"
        - name: ACCESSION_IDS_FILE
          value: "/data/metadata/ids_gwas.txt"
        # Core GAPIT parameters (v3.0.0 naming)
        - name: MODEL
          value: "BLINK,FarmCPU"
        - name: PCA_TOTAL
          value: "3"
        - name: SNP_MAF
          value: "0"
        - name: SNP_THRESHOLD
          value: "0.05"
        - name: SNP_FDR
          value: "{{ SNP_FDR }}"  # Optional: FDR threshold (0.0-1.0), empty to disable
        # Advanced GAPIT parameters
        - name: KINSHIP_ALGORITHM
          value: "Zhang"
        - name: SNP_EFFECT
          value: "Add"
        - name: SNP_IMPUTE
          value: "Middle"
        - name: OUTPUT_PATH
          value: "/outputs"

        # Volume mounts
        volumeMounts:
        - name: nfs-data
          mountPath: /data
          readOnly: true  # Genotype/phenotype data is read-only
        - name: nfs-outputs
          mountPath: /outputs
          readOnly: false  # Need write access for results

      # Volume definitions
      volumes:
      - name: nfs-data
        nfs:
          server: "{{ NFS_SERVER }}"
          path: "{{ NFS_DATA_PATH }}"
      - name: nfs-outputs
        nfs:
          server: "{{ NFS_SERVER }}"
          path: "{{ NFS_OUTPUT_PATH }}"
