apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gapit3-test-  # Argo will append unique ID
  namespace: runai-talmo-lab
  labels:
    pipeline: gapit3-gwas
    stage: test
spec:
  # ===========================================================================
  # GAPIT3 GWAS - Test Pipeline (3 Traits)
  # ===========================================================================
  # Test workflow for validating pipeline before running all 186 traits
  # Runs 3 traits in parallel: indices 2, 3, 4
  #
  # NOTE: Resource allocation (CPU, memory) is configured in WorkflowTemplate:
  #   cluster/argo/workflow-templates/gapit3-single-trait-template.yaml
  # ===========================================================================

  entrypoint: test-pipeline
  serviceAccountName: default

  # Workflow-level parameters (customize these!)
  # Parameter naming follows GAPIT v3.0.0 conventions (see docs/GAPIT_PARAMETERS.md)
  arguments:
    parameters:
    - name: image
      value: "ghcr.io/salk-harnessing-plants-initiative/gapit3-gwas-pipeline:sha-539fe5c-test"
    - name: data-hostpath
      value: "/hpi/hpi_dev/users/eberrigan/20251107_GAPIT_pipeline_tests/data"
    - name: output-hostpath
      value: "/hpi/hpi_dev/users/eberrigan/20251107_GAPIT_pipeline_tests/outputs"
    # Data file paths (relative to /data mount point)
    - name: genotype-file
      value: "/data/genotype/acc_snps_filtered_maf_perl_edited_diploid.hmp.txt"
    - name: phenotype-file
      value: "/data/phenotype/iron_traits_edited.txt"
    - name: accession-ids-file
      value: "/data/metadata/ids_gwas.txt"
    # GAPIT parameters (v3.0.0 naming)
    - name: model
      value: "BLINK,FarmCPU,MLM"
    - name: pca-total
      value: "3"
    - name: snp-maf
      value: "0"
    - name: snp-fdr
      value: "0.05"  # 5% FDR threshold (Benjamini-Hochberg correction)
    # Advanced GAPIT parameters
    - name: kinship-algorithm
      value: "Zhang"
    - name: snp-effect
      value: "Add"
    - name: snp-impute
      value: "Middle"

  # Global timeout
  activeDeadlineSeconds: 14400  # 4 hours max

  # Workflow-level volumes
  volumes:
  - name: nfs-data
    hostPath:
      path: "{{workflow.parameters.data-hostpath}}"
      type: Directory
  - name: nfs-outputs
    hostPath:
      path: "{{workflow.parameters.output-hostpath}}"
      type: DirectoryOrCreate

  templates:
  # ===========================================================================
  # Main DAG: Validation → Extract Traits → Run 3 Traits in Parallel
  # ===========================================================================
  - name: test-pipeline
    dag:
      tasks:
      # Step 1: Validate inputs
      - name: validate-inputs
        template: validate

      # Step 2: Extract trait manifest (depends on validation)
      - name: extract-traits
        dependencies: [validate-inputs]
        template: extract-traits-inline

      # Step 3: Run 3 test traits in parallel
      - name: run-trait-2
        dependencies: [extract-traits]
        templateRef:
          name: gapit3-gwas-single-trait
          template: run-gwas
        arguments:
          parameters:
          - name: trait-index
            value: "2"
          - name: trait-name
            value: "test-trait-2"
          - name: image
            value: "{{workflow.parameters.image}}"
          - name: genotype-file
            value: "{{workflow.parameters.genotype-file}}"
          - name: phenotype-file
            value: "{{workflow.parameters.phenotype-file}}"
          - name: accession-ids-file
            value: "{{workflow.parameters.accession-ids-file}}"
          - name: model
            value: "{{workflow.parameters.model}}"
          - name: pca-total
            value: "{{workflow.parameters.pca-total}}"
          - name: snp-maf
            value: "{{workflow.parameters.snp-maf}}"
          - name: snp-fdr
            value: "{{workflow.parameters.snp-fdr}}"
          - name: kinship-algorithm
            value: "{{workflow.parameters.kinship-algorithm}}"
          - name: snp-effect
            value: "{{workflow.parameters.snp-effect}}"
          - name: snp-impute
            value: "{{workflow.parameters.snp-impute}}"

      - name: run-trait-3
        dependencies: [extract-traits]
        templateRef:
          name: gapit3-gwas-single-trait
          template: run-gwas
        arguments:
          parameters:
          - name: trait-index
            value: "3"
          - name: trait-name
            value: "test-trait-3"
          - name: image
            value: "{{workflow.parameters.image}}"
          - name: genotype-file
            value: "{{workflow.parameters.genotype-file}}"
          - name: phenotype-file
            value: "{{workflow.parameters.phenotype-file}}"
          - name: accession-ids-file
            value: "{{workflow.parameters.accession-ids-file}}"
          - name: model
            value: "{{workflow.parameters.model}}"
          - name: pca-total
            value: "{{workflow.parameters.pca-total}}"
          - name: snp-maf
            value: "{{workflow.parameters.snp-maf}}"
          - name: snp-fdr
            value: "{{workflow.parameters.snp-fdr}}"
          - name: kinship-algorithm
            value: "{{workflow.parameters.kinship-algorithm}}"
          - name: snp-effect
            value: "{{workflow.parameters.snp-effect}}"
          - name: snp-impute
            value: "{{workflow.parameters.snp-impute}}"

      - name: run-trait-4
        dependencies: [extract-traits]
        templateRef:
          name: gapit3-gwas-single-trait
          template: run-gwas
        arguments:
          parameters:
          - name: trait-index
            value: "4"
          - name: trait-name
            value: "test-trait-4"
          - name: image
            value: "{{workflow.parameters.image}}"
          - name: genotype-file
            value: "{{workflow.parameters.genotype-file}}"
          - name: phenotype-file
            value: "{{workflow.parameters.phenotype-file}}"
          - name: accession-ids-file
            value: "{{workflow.parameters.accession-ids-file}}"
          - name: model
            value: "{{workflow.parameters.model}}"
          - name: pca-total
            value: "{{workflow.parameters.pca-total}}"
          - name: snp-maf
            value: "{{workflow.parameters.snp-maf}}"
          - name: snp-fdr
            value: "{{workflow.parameters.snp-fdr}}"
          - name: kinship-algorithm
            value: "{{workflow.parameters.kinship-algorithm}}"
          - name: snp-effect
            value: "{{workflow.parameters.snp-effect}}"
          - name: snp-impute
            value: "{{workflow.parameters.snp-impute}}"

  # ===========================================================================
  # Template: Validation
  # ===========================================================================
  - name: validate
    container:
      image: "{{workflow.parameters.image}}"
      imagePullPolicy: Always
      command: ["/scripts/entrypoint.sh"]
      args: ["validate"]

      env:
      - name: GENOTYPE_FILE
        value: "{{workflow.parameters.genotype-file}}"
      - name: PHENOTYPE_FILE
        value: "{{workflow.parameters.phenotype-file}}"
      - name: ACCESSION_IDS_FILE
        value: "{{workflow.parameters.accession-ids-file}}"

      volumeMounts:
      - name: nfs-data
        mountPath: /data
        readOnly: true

      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

  # ===========================================================================
  # Template: Extract trait names (inline version)
  # ===========================================================================
  - name: extract-traits-inline
    container:
      image: "{{workflow.parameters.image}}"
      imagePullPolicy: Always
      command: ["/scripts/entrypoint.sh"]
      args:
        - "extract-traits"
        - "{{workflow.parameters.phenotype-file}}"
        - "/outputs/traits_manifest.yaml"

      volumeMounts:
      - name: nfs-data
        mountPath: /data
        readOnly: true
      - name: nfs-outputs
        mountPath: /outputs

      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
